In [7]:

import numpy as np 
import pandas as pd

In [8]:

data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}
df= pd.DataFrame(data)
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    740     63   John  January      Q1
1  2023-01-02       B   West    689     27   Mary  January      Q1
2  2023-01-03       C  North    336     80    Bob  January      Q1
3  2023-01-04       D  South    814     68  Alice  January      Q1
4  2023-01-05       A   East    610     26   John  January      Q1
5  2023-01-06       B   West    186     53   Mary  January      Q1
6  2023-01-07       C  North    884     39    Bob  January      Q1
7  2023-01-08       D  South    831     35  Alice  January      Q1
8  2023-01-09       A   East    860     96   John  January      Q1
9  2023-01-10       B   West    880     77   Mary  January      Q1
10 2023-01-11       C  North    888     50    Bob  January      Q1
11 2023-01-12       D  South    921     57  Alice  January      Q1
12 2023-01-13       A   East    713     60   John  January      Q1
13 2023-01-14       B   West    978     63   Mary  January      Q1
14 2023-01-15       C  North    309     68    Bob  January      Q1
15 2023-01-16       D  South    187     93  Alice  January      Q1
16 2023-01-17       A   East    181     61   John  January      Q1
17 2023-01-18       B   West    467     69   Mary  January      Q1
18 2023-01-19       C  North    960     44    Bob  January      Q1
19 2023-01-20       D  South    380     79  Alice  January      Q1

In [9]:
#A pivot table is used when you want to summarize numerical data based on categories.

pd.pivot_table(df, values="Sales" , index='Region' , columns="Product" , aggfunc='median')

Product      A      B      C      D
Region
East     713.0    NaN    NaN    NaN
North      NaN    NaN  884.0    NaN
South      NaN    NaN    NaN  814.0
West       NaN  689.0    NaN    NaN

In [10]:
pivot2=pd.pivot_table(df, values=['Sales' , 'Units'] , index='Region' , columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     620.8    NaN    NaN    NaN  61.2   NaN   NaN   NaN
North      NaN    NaN  675.4    NaN   NaN   NaN  56.2   NaN
South      NaN    NaN    NaN  626.6   NaN   NaN   NaN  66.4
West       NaN  640.0    NaN    NaN   NaN  57.8   NaN   NaN

In [11]:
#cross Tabs 
#diffenrece between crossTabs and pivot_table 

#pd.crosstab() is mainly used to create a frequency/count table between categorical variables.
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [12]:
comparison = pd.DataFrame({
    "Feature": [
        "Main purpose",
        "Default operation",
        "Numerical values",
        "Categorical data",
        "Aggregation",
        "Similar to"
    ],
    "pivot_table()": [
        "Summarization",
        "Mean",
        "Very common",
        "Yes",
        "aggfunc",
        "Excel Pivot Table"
    ],
    "crosstab()": [
        "Frequency / Count",
        "Count",
        "Optional",
        "Yes",
        "aggfunc",
        "Contingency Table"
    ]
})

print(comparison)

             Feature      pivot_table()         crosstab()
0       Main purpose      Summarization  Frequency / Count
1  Default operation               Mean              Count
2   Numerical values        Very common           Optional
3   Categorical data                Yes                Yes
4        Aggregation            aggfunc            aggfunc
5         Similar to  Excel Pivot Table  Contingency Table